// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "Messages.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - RMTMessagesRoot

@implementation RMTMessagesRoot

@end

#pragma mark - RMTMessagesRoot_FileDescriptor

static GPBFileDescriptor *RMTMessagesRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"grpc.testing"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Enum RMTPayloadType

GPBEnumDescriptor *RMTPayloadType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageEnumValueDescription values[] = {
      { .name = "Compressable", .number = RMTPayloadType_Compressable },
      { .name = "Uncompressable", .number = RMTPayloadType_Uncompressable },
      { .name = "Random", .number = RMTPayloadType_Random },
    };
    descriptor = [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(RMTPayloadType)
                                                   values:values
                                               valueCount:sizeof(values) / sizeof(GPBMessageEnumValueDescription)
                                             enumVerifier:RMTPayloadType_IsValidValue];
  }
  return descriptor;
}

BOOL RMTPayloadType_IsValidValue(int32_t value__) {
  switch (value__) {
    case RMTPayloadType_Compressable:
    case RMTPayloadType_Uncompressable:
    case RMTPayloadType_Random:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - RMTPayload

@implementation RMTPayload

@dynamic type;
@dynamic body;

typedef struct RMTPayload__storage_ {
  uint32_t _has_storage_[1];
  RMTPayloadType type;
  NSData *body;
} RMTPayload__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "type",
        .number = RMTPayload_FieldNumber_Type,
        .hasIndex = 0,
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
        .offset = offsetof(RMTPayload__storage_, type),
        .defaultValue.valueEnum = RMTPayloadType_Compressable,
        .dataTypeSpecific.enumDescFunc = RMTPayloadType_EnumDescriptor,
        .fieldOptions = NULL,
      },
      {
        .name = "body",
        .number = RMTPayload_FieldNumber_Body,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
        .offset = offsetof(RMTPayload__storage_, body),
        .defaultValue.valueData = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RMTPayload class]
                                     rootClass:[RMTMessagesRoot class]
                                          file:RMTMessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RMTPayload__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t RMTPayload_Type_RawValue(RMTPayload *message) {
  GPBDescriptor *descriptor = [RMTPayload descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RMTPayload_FieldNumber_Type];
  return GPBGetMessageInt32Field(message, field);
}

void SetRMTPayload_Type_RawValue(RMTPayload *message, int32_t value) {
  GPBDescriptor *descriptor = [RMTPayload descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RMTPayload_FieldNumber_Type];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - RMTSimpleRequest

@implementation RMTSimpleRequest

@dynamic responseType;
@dynamic responseSize;
@dynamic hasPayload, payload;
@dynamic fillUsername;
@dynamic fillOauthScope;

typedef struct RMTSimpleRequest__storage_ {
  uint32_t _has_storage_[1];
  BOOL fillUsername;
  BOOL fillOauthScope;
  RMTPayloadType responseType;
  int32_t responseSize;
  RMTPayload *payload;
} RMTSimpleRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "responseType",
        .number = RMTSimpleRequest_FieldNumber_ResponseType,
        .hasIndex = 0,
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
        .offset = offsetof(RMTSimpleRequest__storage_, responseType),
        .defaultValue.valueEnum = RMTPayloadType_Compressable,
        .dataTypeSpecific.enumDescFunc = RMTPayloadType_EnumDescriptor,
        .fieldOptions = NULL,
      },
      {
        .name = "responseSize",
        .number = RMTSimpleRequest_FieldNumber_ResponseSize,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
        .offset = offsetof(RMTSimpleRequest__storage_, responseSize),
        .defaultValue.valueInt32 = 0,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "payload",
        .number = RMTSimpleRequest_FieldNumber_Payload,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(RMTSimpleRequest__storage_, payload),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(RMTPayload),
        .fieldOptions = NULL,
      },
      {
        .name = "fillUsername",
        .number = RMTSimpleRequest_FieldNumber_FillUsername,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
        .offset = offsetof(RMTSimpleRequest__storage_, fillUsername),
        .defaultValue.valueBool = NO,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "fillOauthScope",
        .number = RMTSimpleRequest_FieldNumber_FillOauthScope,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
        .offset = offsetof(RMTSimpleRequest__storage_, fillOauthScope),
        .defaultValue.valueBool = NO,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RMTSimpleRequest class]
                                     rootClass:[RMTMessagesRoot class]
                                          file:RMTMessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RMTSimpleRequest__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t RMTSimpleRequest_ResponseType_RawValue(RMTSimpleRequest *message) {
  GPBDescriptor *descriptor = [RMTSimpleRequest descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RMTSimpleRequest_FieldNumber_ResponseType];
  return GPBGetMessageInt32Field(message, field);
}

void SetRMTSimpleRequest_ResponseType_RawValue(RMTSimpleRequest *message, int32_t value) {
  GPBDescriptor *descriptor = [RMTSimpleRequest descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RMTSimpleRequest_FieldNumber_ResponseType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - RMTSimpleResponse

@implementation RMTSimpleResponse

@dynamic hasPayload, payload;
@dynamic username;
@dynamic oauthScope;

typedef struct RMTSimpleResponse__storage_ {
  uint32_t _has_storage_[1];
  RMTPayload *payload;
  NSString *username;
  NSString *oauthScope;
} RMTSimpleResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "payload",
        .number = RMTSimpleResponse_FieldNumber_Payload,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(RMTSimpleResponse__storage_, payload),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(RMTPayload),
        .fieldOptions = NULL,
      },
      {
        .name = "username",
        .number = RMTSimpleResponse_FieldNumber_Username,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RMTSimpleResponse__storage_, username),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "oauthScope",
        .number = RMTSimpleResponse_FieldNumber_OauthScope,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RMTSimpleResponse__storage_, oauthScope),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RMTSimpleResponse class]
                                     rootClass:[RMTMessagesRoot class]
                                          file:RMTMessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RMTSimpleResponse__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RMTStreamingInputCallRequest

@implementation RMTStreamingInputCallRequest

@dynamic hasPayload, payload;

typedef struct RMTStreamingInputCallRequest__storage_ {
  uint32_t _has_storage_[1];
  RMTPayload *payload;
} RMTStreamingInputCallRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "payload",
        .number = RMTStreamingInputCallRequest_FieldNumber_Payload,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(RMTStreamingInputCallRequest__storage_, payload),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(RMTPayload),
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RMTStreamingInputCallRequest class]
                                     rootClass:[RMTMessagesRoot class]
                                          file:RMTMessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RMTStreamingInputCallRequest__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RMTStreamingInputCallResponse

@implementation RMTStreamingInputCallResponse

@dynamic aggregatedPayloadSize;

typedef struct RMTStreamingInputCallResponse__storage_ {
  uint32_t _has_storage_[1];
  int32_t aggregatedPayloadSize;
} RMTStreamingInputCallResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "aggregatedPayloadSize",
        .number = RMTStreamingInputCallResponse_FieldNumber_AggregatedPayloadSize,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
        .offset = offsetof(RMTStreamingInputCallResponse__storage_, aggregatedPayloadSize),
        .defaultValue.valueInt32 = 0,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RMTStreamingInputCallResponse class]
                                     rootClass:[RMTMessagesRoot class]
                                          file:RMTMessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RMTStreamingInputCallResponse__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RMTResponseParameters

@implementation RMTResponseParameters

@dynamic size;
@dynamic intervalUs;

typedef struct RMTResponseParameters__storage_ {
  uint32_t _has_storage_[1];
  int32_t size;
  int32_t intervalUs;
} RMTResponseParameters__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "size",
        .number = RMTResponseParameters_FieldNumber_Size,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
        .offset = offsetof(RMTResponseParameters__storage_, size),
        .defaultValue.valueInt32 = 0,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "intervalUs",
        .number = RMTResponseParameters_FieldNumber_IntervalUs,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
        .offset = offsetof(RMTResponseParameters__storage_, intervalUs),
        .defaultValue.valueInt32 = 0,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RMTResponseParameters class]
                                     rootClass:[RMTMessagesRoot class]
                                          file:RMTMessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RMTResponseParameters__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RMTStreamingOutputCallRequest

@implementation RMTStreamingOutputCallRequest

@dynamic responseType;
@dynamic responseParametersArray, responseParametersArray_Count;
@dynamic hasPayload, payload;

typedef struct RMTStreamingOutputCallRequest__storage_ {
  uint32_t _has_storage_[1];
  RMTPayloadType responseType;
  NSMutableArray *responseParametersArray;
  RMTPayload *payload;
} RMTStreamingOutputCallRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "responseType",
        .number = RMTStreamingOutputCallRequest_FieldNumber_ResponseType,
        .hasIndex = 0,
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
        .offset = offsetof(RMTStreamingOutputCallRequest__storage_, responseType),
        .defaultValue.valueEnum = RMTPayloadType_Compressable,
        .dataTypeSpecific.enumDescFunc = RMTPayloadType_EnumDescriptor,
        .fieldOptions = NULL,
      },
      {
        .name = "responseParametersArray",
        .number = RMTStreamingOutputCallRequest_FieldNumber_ResponseParametersArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(RMTStreamingOutputCallRequest__storage_, responseParametersArray),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(RMTResponseParameters),
        .fieldOptions = NULL,
      },
      {
        .name = "payload",
        .number = RMTStreamingOutputCallRequest_FieldNumber_Payload,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(RMTStreamingOutputCallRequest__storage_, payload),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(RMTPayload),
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RMTStreamingOutputCallRequest class]
                                     rootClass:[RMTMessagesRoot class]
                                          file:RMTMessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RMTStreamingOutputCallRequest__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t RMTStreamingOutputCallRequest_ResponseType_RawValue(RMTStreamingOutputCallRequest *message) {
  GPBDescriptor *descriptor = [RMTStreamingOutputCallRequest descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RMTStreamingOutputCallRequest_FieldNumber_ResponseType];
  return GPBGetMessageInt32Field(message, field);
}

void SetRMTStreamingOutputCallRequest_ResponseType_RawValue(RMTStreamingOutputCallRequest *message, int32_t value) {
  GPBDescriptor *descriptor = [RMTStreamingOutputCallRequest descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RMTStreamingOutputCallRequest_FieldNumber_ResponseType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - RMTStreamingOutputCallResponse

@implementation RMTStreamingOutputCallResponse

@dynamic hasPayload, payload;

typedef struct RMTStreamingOutputCallResponse__storage_ {
  uint32_t _has_storage_[1];
  RMTPayload *payload;
} RMTStreamingOutputCallResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "payload",
        .number = RMTStreamingOutputCallResponse_FieldNumber_Payload,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(RMTStreamingOutputCallResponse__storage_, payload),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(RMTPayload),
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RMTStreamingOutputCallResponse class]
                                     rootClass:[RMTMessagesRoot class]
                                          file:RMTMessagesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RMTStreamingOutputCallResponse__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
