source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'

target 'RouteGuideClient' do
  pod 'Protobuf', :path => "../../../third_party/protobuf"
  pod 'BoringSSL', :podspec => "../../../src/objective-c"
  pod 'gRPC', :path => "../../.."
  # Depend on the generated RouteGuide library.
  pod 'RouteGuide', :path => '.'
end
